### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by hazcod** [attwad/nessie#6]
Hi, would it be possible to document a full example on how to setup a new scan for a new target?
The `nessus.NewScan(...)` call mentions some parameters which does not seem to come from your library. Thanks!

**Comment by attwad** [comment]
Hi, Nessus 6 is many years old (released in 2013!), I'd not recommend using it nowadays, please ignore this library that I wrote at the time nessus 6 was a thing.
https://docs.tenable.com/releasenotes/Content/nessus/nessus.htm
I haven't looked at the current nessus APIs but I suspect they have a more comprehensive set of client libraries now that you should be able to use.
